### ISSUE TITLE
Direct Immigration in new patch is broken

### ISSUE THREAD

**Issue by lachlanMarine** [The-Grand-Combination/The-Grand-Combo#114]
I've been trying for half a day now experimenting with different versions and modifying the game files. Immigration is not specific and for some reason provinces with immigrators (to move out of) like to move to desert provinces. there was one instance where immigration sort of worked at the very start of the game but after a year (1837) it stopped working again and went back to normal. Also the immigration selector has no effect (this is taking in account for the admin and education sliders)

**Comment by onurozko** [comment]
Changing certain values under \Victoria 2\mod\TGC\map\terrain.txt solves the problem:

There should be no lower value for immigrant_attract than -0.9 since it overflows when combined with -100 attraction bonus of the immigrator. 


[terrain.txt](https://github.com/rderekp/The-Grand-Combo/files/6673373/terrain.txt)

**Comment by emprahtheodosius** [comment]
I've fixed this particular issue months ago, but forgot to push it to the repository. It is fixed now.
